-- English lexicon imported from VERBS.pdf.
-- Run this in Supabase SQL Editor before importing if the table does not exist.

create extension if not exists pgcrypto;

create table if not exists public.english_lexicon_items (
  id uuid primary key default gen_random_uuid(),
  source_doc text not null,
  category text not null,
  term text not null,
  base_verb text,
  past text,
  past_participle text,
  meaning_es text,
  definition_en text,
  example_en text,
  notes text,
  source_page integer,
  raw_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_doc, category, term)
);

alter table public.english_lexicon_items enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'english_lexicon_items'
      and policyname = 'Allow public read english lexicon'
  ) then
    create policy "Allow public read english lexicon"
    on public.english_lexicon_items
    for select
    using (true);
  end if;
end $$;


delete from public.english_lexicon_items
where source_doc = 'VERBS.pdf';

insert into public.english_lexicon_items (
  source_doc, category, term, base_verb, past, past_participle, meaning_es, definition_en, example_en, notes, source_page, raw_text
)
values
('VERBS.pdf', 'common_verb', 'Ride', 'RIDE', 'RODE', 'RIDDEN', 'MONTAR, ANDAR EN', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Get', 'GET', 'GOT', 'GOTTEN', 'OBTENER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Give', 'GIVE', 'GAVE', 'GIVEN', 'DAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'See', 'SEE', 'SAW', 'SEEN', 'VER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Look', 'LOOK', 'LOOKED', 'LOOKED', 'OBSERVAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Take', 'TAKE', 'TOOK', 'TAKEN', 'TOMAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Think', 'THINK', 'THOUGHT', 'THOUGHT', 'PENSAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Wash', 'WASH', 'WASHED', 'WASHED', 'LAVAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Have', 'HAVE', 'HAD', 'HAD', 'TENER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Find', 'FIND', 'FOUND', 'FOUND', 'ENCONTRAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Learn', 'LEARN', 'LEARNED', 'LEARNED', 'APRENDER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Write', 'WRITE', 'WROTE', 'WRITTEN', 'ESCRIBIR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Walk', 'WALK', 'WALKED', 'WALKED', 'CAMINAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Can', 'CAN', 'COULD', null, 'PODER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Want', 'WANT', 'WANTED', 'WANTED', 'QUERER, DESEAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Need', 'NEED', 'NEEDED', 'NEEDED', 'NECESITAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Like', 'LIKE', 'LIKED', 'LIKED', 'GUSTAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Talk', 'TALK', 'TALKED', 'TALKED', 'CONVERSAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Speak', 'SPEAK', 'SPOKE', 'SPOKEN', 'HABLAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Remember', 'REMEMBER', 'REMEMBERED', 'REMEMBERED', 'RECORDAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Understand', 'UNDERSTAND', 'UNDERSTOOD', 'UNDERSTOOD', 'ENTENDER', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Spend', 'SPEND', 'SPENT', 'SPENT', 'GASTAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Try', 'TRY', 'TRIED', 'TRIED', 'INTENTAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Swim', 'SWIM', 'SWAM', 'SWUM', 'NADAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Start', 'START', 'STARTED', 'STARTED', 'EMPEZAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Say', 'SAY', 'SAID', 'SAID', 'DECIR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Tell', 'TELL', 'TOLD', 'TOLD', 'NARRAR, CONTAR', null, null, null, 3, null),
('VERBS.pdf', 'common_verb', 'Buy', 'BUY', 'BOUGHT', 'BOUGHT', 'COMPRAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Bring', 'BRING', 'BROUGHT', 'BROUGHT', 'TRAER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Change', 'CHANGE', 'CHANGED', 'CHANGED', 'CAMBIAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Cut', 'CUT', 'CUT', 'CUT', 'CORTAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Fall', 'FALL', 'FELL', 'FALLEN', 'CAER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Fix', 'FIX', 'FIXED', 'FIXED', 'REPARAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Forget', 'FORGET', 'FORGOT', 'FORGOTTEN', 'OLVIDAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Lose', 'LOSE', 'LOST', 'LOST', 'PERDER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Open', 'OPEN', 'OPENED', 'OPENED', 'ABRIR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Close', 'CLOSE', 'CLOSED', 'CLOSED', 'CERRAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Pay', 'PAY', 'PAID', 'PAID', 'PAGAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Put', 'PUT', 'PUT', 'PUT', 'PONER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Run', 'RUN', 'RAN', 'RUN', 'CORRER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Send', 'SEND', 'SENT', 'SENT', 'ENVIAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Feel', 'FEEL', 'FELT', 'FELT', 'SENTIR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Teach', 'TEACH', 'TAUGHT', 'TAUGHT', 'ENSEÑAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Wait', 'WAIT', 'WAITED', 'WAITED', 'ESPERAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Fly', 'FLY', 'FLEW', 'FLOWN', 'VOLAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Leave', 'LEAVE', 'LEFT', 'LEFT', 'DEJAR, SALIR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Know', 'KNOW', 'KNEW', 'KNOWN', 'SABER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Believe', 'BELIEVE', 'BELIEVED', 'BELIEVED', 'CREER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Become', 'BECOME', 'BECAME', 'BECOME', 'LLEGAR A SER', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Ask', 'ASK', 'ASKED', 'ASKED', 'PEDIR, PREGUNTAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Hear', 'HEAR', 'HEARD', 'HEARD', 'ESCUCHAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Use', 'USE', 'USED', 'USED', 'USAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Sing', 'SING', 'SANG', 'SUNG', 'CANTAR', null, null, null, 4, null),
('VERBS.pdf', 'common_verb', 'Pick Up', 'PICK UP', 'PICKED UP', 'PICKED UP', 'RECOGER', null, null, null, 4, null),
('VERBS.pdf', 'irregular_verb', 'Arise', 'ARISE', 'AROSE', 'ARISEN', 'ELEVARSE, SURGIR, ORIGINARSE.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Awake', 'AWAKE', 'AWOKE', 'AWOKEN', 'DESPERTAR, MOVER, EXCITAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bear', 'BEAR', 'BORE', 'BORN', 'SOPORTAR, SOSTENER, TOLERAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Beat', 'BEAT', 'BEAT', 'BEATEN', 'BATIR, REVOLVER, GOLPEAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Become', 'BECOME', 'BECAME', 'BECOME', 'HACERSE, CONVERTIRSE EN.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Begin', 'BEGIN', 'BEGAN', 'BEGUN', 'EMPEZAR, INICIAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bend', 'BEND', 'BENT', 'BENT', 'DOBLAR, INCLINAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bet', 'BET', 'BET', 'BET', 'APOSTAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bind', 'BIND', 'BOUND', 'BOUND', 'ATAR, UNIR, ENLAZAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bite', 'BITE', 'BIT', 'BITTEN', 'MORDER.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Blow', 'BLOW', 'BLEW', 'BLOWN', 'SOPLAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Break', 'BREAK', 'BROKE', 'BROKEN', 'QUEBRAR, PARTIR, ROMPER.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Bring', 'BRING', 'BROUGHT', 'BROUGHT', 'TRAER, LLEVAR, CONDUCIR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Build', 'BUILD', 'BUILT', 'BUILT', 'CONSTRUIR, EDIFICAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Burn', 'BURN', 'BURNT', 'BURNT', 'QUEMAR, INCENDIAR', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Burst', 'BURST', 'BURST', 'BURST', 'ROMPER, REVENTAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Buy', 'BUY', 'BOUGHT', 'BOUGHT', 'COMPRAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Catch', 'CATCH', 'CAUGHT', 'CAUGHT', 'COGER, ATRAPAR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Choose', 'CHOOSE', 'CHOSE', 'CHOSEN', 'ESCOGER, ELEGIR.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Cling', 'CLING', 'CLUNG', 'CLUNG', 'ASIRSE, ADHERIRSE, PEGARSE.', null, null, null, 5, null),
('VERBS.pdf', 'irregular_verb', 'Come', 'COME', 'CAME', 'COME', 'VENIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Cost', 'COST', 'COST', 'COST', 'COSTAR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Creep', 'CREEP', 'CREPT', 'CREPT', 'ARRASTRARSE, PEGARSE.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Cut', 'CUT', 'CUT', 'CUT', 'CORTAR, DIVIDIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Deal', 'DEAL', 'DEALT', 'DEALT', 'TRATAR, TENER QUE REFERIRSE', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Dig', 'DIG', 'DUG', 'DUG', 'CAVAR, AHONDAR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Do', 'DO', 'DID', 'DONE', 'HACER, EJECUTAR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Draw', 'DRAW', 'DREW', 'DRAWN', 'DIBUJAR, ATRAER.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Drink', 'DRINK', 'DRANK', 'DRUNK', 'BEBER', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Drive', 'DRIVE', 'DROVE', 'DRIVEN', 'CONDUCIR, LLEVAR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Fall', 'FALL', 'FELL', 'FALLEN', 'CAER, DISMINUIR', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Feed', 'FEED', 'FED', 'FED', 'ALIMENTAR, NUTRIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Feel', 'FEEL', 'FELT', 'FELT', 'SENTIR', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Fight', 'FIGHT', 'FOUGHT', 'FOUGHT', 'PELEAR, COMBATIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Find Out', 'FIND OUT', 'FOUND OUT', 'FOUND OUT', 'ENCONTRAR, DESCUBRIR', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Flee', 'FLEE', 'FLED', 'FLED', 'ESCAPAR, HUIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Fly', 'FLY', 'FLEW', 'FLOWN', 'VOLAR', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Forbid', 'FORBID', 'FORBADE', 'FORBIDDEN', 'PROHIBIR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Foresee', 'FORESEE', 'FORESAW', 'FORESEEN', 'PREVER, PREVENIR', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Forget', 'FORGET', 'FORGOT', 'FORGOTTEN', 'OLVIDAR.', null, null, null, 6, null),
('VERBS.pdf', 'irregular_verb', 'Freeze', 'FREEZE', 'FROZE', 'FROZEN', 'CONGELAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Get', 'GET', 'GOT', 'GOTTEN', 'LOGRAR, OBTENER, CONSEGUIR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Give', 'GIVE', 'GAVE', 'GIVEN', 'DAR, CONCEDER', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Go', 'GO', 'WENT', 'GONE', 'IR, FUNCIONAR, RESULTAR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Grind', 'GRIND', 'GROUND', 'GROUND', 'MOLER, TRITURAR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Grow', 'GROW', 'GREW', 'GROWN', 'CRECER, CULTIVAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hang', 'HANG', 'HUNG', 'HUNG', 'COLGAR, SUSPENDER.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Have', 'HAVE', 'HAD', 'HAD', 'TENER, HABER.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hear', 'HEAR', 'HEARD', 'HEARD', 'OIR, ESCUCHAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hide', 'HIDE', 'HID', 'HIDDEN', 'OCULTAR, ENCUBRIR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hit', 'HIT', 'HIT', 'HIT', 'PEGAR, GOLPEAR, ACERTAR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hold', 'HOLD', 'HELD', 'HELD', 'SOSTENER, MANTENER.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Hurt', 'HURT', 'HURT', 'HURT', 'PEGAR, GOLPEAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Keep', 'KEEP', 'KEPT', 'KEPT', 'MANTENER, GUARDAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Know', 'KNOW', 'KNEW', 'KNOWN', 'CONOCER, SABER', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Lay', 'LAY', 'LAID', 'LAID', 'PONER, COLOCAR.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Lead', 'LEAD', 'LED', 'LED', 'GUIAR, LLEVAR, CONDUCIR', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Lean', 'LEAN', 'LEANT', 'LEANT', 'INCLINAR, APOYARSE.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Leave', 'LEAVE', 'LEFT', 'LEFT', 'DEJAR, IRSE.', null, null, null, 7, null),
('VERBS.pdf', 'irregular_verb', 'Lend', 'LEND', 'LENT', 'LENT', 'PRESTAR.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Let', 'LET', 'LET', 'LET', 'PERMITIR, CONCEDER.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Lie', 'LIE', 'LIED', 'LIED', 'MENTIR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Light', 'LIGHT', 'LIT', 'LIT', 'ENCENDER, ALUMBRAR, ILUMINAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Lose', 'LOSE', 'LOST', 'LOST', 'PERDER, MALGASTAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Make', 'MAKE', 'MADE', 'MADE', 'HACER, PRODUCIR.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Mean', 'MEAN', 'MEANT', 'MEANT', 'SIGNIFICAR, QUERER DECIR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Meet', 'MEET', 'MET', 'MET', 'ENCONTRARSE, CONOCER', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Melt', 'MELT', 'MELTED', 'MOLTEN', 'DERRETIR, FUNDIR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Mistake', 'MISTAKE', 'MISTOOK', 'MISTAKEN', 'EQUIVOCARSE, ERRAR.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Misunderstand', 'MISUNDERSTAND', 'MISUNDERSTOOD', 'MISUNDERSTOOD', 'ENTENDER MAL', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Overcome', 'OVERCOME', 'OVERCAME', 'OVERCOME', 'VENCER, SUPERAR.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Pay', 'PAY', 'PAID', 'PAID', 'PAGAR, RECOMPENSAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Put', 'PUT', 'PUT', 'PUT', 'PONER, COLOCAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Read', 'READ', 'READ', 'READ', 'LEER, MARCAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Rebuild', 'REBUILD', 'REBUILT', 'REBUILT', 'RECONSTRUIR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Rid', 'RID', 'RID', 'RID', 'LIBERARSE, ZAFARSE', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Ride', 'RIDE', 'RODE', 'RIDDEN', 'RODAR, FUNCIONAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Ring', 'RING', 'RANG', 'RUNG', 'TOCAR, SONAR', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Rise', 'RISE', 'ROSE', 'RISEN', 'ASCENDER, LEVANTAR.', null, null, null, 8, null),
('VERBS.pdf', 'irregular_verb', 'Run', 'RUN', 'RAN', 'RUN', 'CORRER, FUNCIONAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Saw', 'SAW', 'SAWED', 'SAWN', 'ASERRAR, CORTAR CON SIERRA', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Say', 'SAY', 'SAID', 'SAID', 'DECIR, AFIRMAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'See', 'SEE', 'SAW', 'SEEN', 'VER, OBSERVAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Seek', 'SEEK', 'SOUGHT', 'SOUGHT', 'BUSCAR, SOLICITAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Sell', 'SELL', 'SOLD', 'SOLD', 'VENDER', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Send', 'SEND', 'SENT', 'SENT', 'ENVIAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Set', 'SET', 'SET', 'SET', 'INSTALAR, COLOCAR, FIJAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shake', 'SHAKE', 'SHOOK', 'SHAKEN', 'SACUDIR, LANZAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shed', 'SHED', 'SHED', 'SHED', 'DERRAMAR, DEJAR CAER', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shine', 'SHINE', 'SHONE', 'SHONE', 'BRILLAR, SOBRESALIR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shoot', 'SHOOT', 'SHOT', 'SHOT', 'DISPARAR, LANZAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Show', 'SHOW', 'SHOWED', 'SHOWED', 'MOSTRAR, PROBAR, DEMOSTRAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shrink', 'SHRINK', 'SHRANK', 'SHRUNK', 'ENCOGERSE, DISMINUIR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Shut', 'SHUT', 'SHUT', 'SHUT', 'CERRAR, IMPEDIR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Sing', 'SING', 'SANG', 'SUNG', 'CANTAR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Sink', 'SINK', 'SANK', 'SUNK', 'HUNDIR, SUMERGIR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Sit', 'SIT', 'SAT', 'SAT', 'SENTARSE, REUNIRSE', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Sleep', 'SLEEP', 'SLEPT', 'SLEPT', 'DORMIR', null, null, null, 9, null),
('VERBS.pdf', 'irregular_verb', 'Slide', 'SLIDE', 'SLID', 'SLID', 'RESBALAR, DESLIZAR.', null, null, null, 9, null),
('VERBS.pdf', 'phrasal_verb', 'Break In On', null, null, null, null, 'Interrupt (a conversation).', 'I was talking to Mom on the phone when the operator broke in on our call.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Catch Up With', null, null, null, null, 'Keep abreast.', 'After our month-long trip, it was time to catch up with the neighbors and the news around town', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Check Up On', null, null, null, null, 'Examine, investigate.', 'The boys promised to check up on the condition of the summer house from time to time.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Come Up With', null, null, null, null, 'To contribute (suggestion, money).', 'After years of giving nothing, the old parishioner was able to come up with a thousand-dollar donation.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Cut Down On', null, null, null, null, 'Curtail (expenses).', 'We tried to cut down on the money we were spending on entertainment.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Drop Out Of', null, null, null, null, 'Leave school.', 'I hope none of my students drop out of school this semester.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Get Along With', null, null, null, null, 'Have a good relationship with.', 'I found it very hard to get along with my brother when we were young.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Get Away With', null, null, null, null, 'Escape, blame.', 'Janik cheated on the exam and then tried to get away with it.', null, 12, null),
('VERBS.pdf', 'phrasal_verb', 'Get Rid Of', null, null, null, null, 'Eliminate.', 'The citizens tried to get rid of their corrupt mayor in the recent election.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Get Through With', null, null, null, null, 'Finish.', 'When will you ever get through with that program?', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Keep Up With', null, null, null, null, 'Maintain pace with.', 'It''s hard to keep up with the Joneses when you lose your job!', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Look Forward To', null, null, null, null, 'Anticipate with pleasure.', 'I always look forward to the beginning of a new semester.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Look Down On', null, null, null, null, 'Despise.', 'It''s typical of a jingoistic country that the citizens look down on their geographical neighbors.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Look In On', null, null, null, null, 'Visit (somebody).', 'We were going to look in on my brother-in-law, but he wasn''t home.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Look Out For', null, null, null, null, 'Be careful, anticipate.', 'Good instructors will look out for early signs of failure in their students.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Look Up To', null, null, null, null, 'Respect.', 'First-graders really look up to their teachers.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Make Sure Of', null, null, null, null, 'Verify.', 'Make sure of the student''s identity before you let him into the classroom.', null, 13, null),
('VERBS.pdf', 'phrasal_verb', 'Put Up With', null, null, null, null, 'Tolerate.', 'The teacher had to put up with a great deal of nonsense from the new students.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Run Out Of', null, null, null, null, 'Exhaust, supply.', 'The runners ran out of energy before the end of the race.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Take Care Of', null, null, null, null, 'Be responsible for.', 'My oldest sister took care of us, after Mom died.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Talk Back To', null, null, null, null, 'Answer impolitely.', 'The star player talked back to the coach and was thrown off the team.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Think Back On', null, null, null, null, 'Recall.', 'I often think back on my childhood with great pleasure.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Walk Out On', null, null, null, null, 'Abandon.', 'Her husband walked out on her and their three children.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Pass Out', null, null, null, null, 'Lose consciousness, faint.', 'He had drunk too much; he passed out on the sidewalk outside the bar.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Show Off', null, null, null, null, 'Demonstrate something proudly.', 'Whenever he sat down at the piano, we knew he was going to show off.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Show Up', null, null, null, null, 'Arrive.', 'Day after day, Efrain showed up for class twenty minutes late.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Wake Up', null, null, null, null, 'Awake from sleep.', 'I woke up when the rooster crowed.', null, 14, null),
('VERBS.pdf', 'phrasal_verb', 'Break Down', null, null, null, null, 'Stop functioning.', 'That old Jeep had a tendency to break down just when I needed it the most.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Catch On', null, null, null, null, 'Become popular.', 'Popular songs seem to catch on in California first and then spread eastward.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Come Back', null, null, null, null, 'Return to a place.', 'Father promised that we would never come back to this horrible place.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Come In', null, null, null, null, 'Enter.', 'They tried to come in through the back door, but it was locked.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Come To', null, null, null, null, 'Regain consciousness.', 'He was hit on the head very hard, but after several minutes, he started to come to again.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Come Over', null, null, null, null, 'To visit.', 'The children promised to come over, but they never do.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Drop By', null, null, null, null, 'Visit without appointment.', 'We used to just drop by, but they were never home, so we stopped doing that.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Eat Out', null, null, null, null, 'Eat in a restaurant.', 'When we visited Paris, we loved eating out in the sidewalk cafes.', null, 15, null),
('VERBS.pdf', 'phrasal_verb', 'Get By', null, null, null, null, 'Survive.', 'Uncle Heine didn''t have much money, but he always seemed to get by without borrowing money from relatives.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Get Up', null, null, null, null, 'Arise.', 'Grandmother tried to get up, but the couch was too low, and she couldn''t make it on her own.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Go Back', null, null, null, null, 'Return to a place.', 'It''s hard to imagine that we will ever go back to Lithuania.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Go On', null, null, null, null, 'Continue.', 'He would finish one Dickens novel and then just go on to the next.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Go On (2)', null, null, null, null, 'Happen.', 'The cops heard all the noise and stopped to see what was going on.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Grow Up', null, null, null, null, 'Get older.', 'Charles grew up to be a lot like his father.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Keep Away', null, null, null, null, 'Remain at a distance.', 'The judge warned the stalker to keep away from his victim''s home.', null, 16, null),
('VERBS.pdf', 'phrasal_verb', 'Keep On (With Gerund)', null, null, null, null, 'Continue with the same.', 'He tried to keep on singing long after his voice was ruined.', null, 16, null),
('VERBS.pdf', 'idiom', 'About To (Do Something) According To (Someone Or Something)', null, null, null, 'A PUNTO DE', 'To be on the point of doing something', 'I was about to leave when the phone rang. - DE ACUERDO A As said or told by someone, in agreement with something, in the order of something, in proportion to something  According to our teacher, there will be no class next week.', null, null, 'ABOUT TO (DO SOMETHING) - A PUNTO DE ACCORDING TO (SOMEONE OR SOMETHING)'),
('VERBS.pdf', 'idiom', 'Account For (Something)', null, null, null, 'EXPLICAR', 'To provide an explanation or an answer for something', 'The bad weather accounts for the fact that few people came to the meeting.', null, null, 'ACCOUNT FOR (SOMETHING) - EXPLICAR'),
('VERBS.pdf', 'idiom', 'After All', null, null, null, 'DESPUÉS DE TODO', 'Considering the fact that something happened or happens, something that is usually assumed', '“You don’t need to phone him. After all, he never phones you.”', null, null, 'AFTER ALL - DESPUÉS DE TODO'),
('VERBS.pdf', 'idiom', 'All Of A Sudden', null, null, null, 'DE REPENTE', 'Suddenly, without advance warning', 'All of a sudden, it became cloudy and began to rain.', null, null, 'ALL OF A SUDDEN - DE REPENTE'),
('VERBS.pdf', 'idiom', 'As A Matter Of Fact', null, null, null, 'DE HECHO', 'Actually', '“As a matter of fact, we have been to the sports stadium many times.”', null, null, 'AS A MATTER OF FACT - DE HECHO'),
('VERBS.pdf', 'idiom', 'As Far As', null, null, null, 'I KNOW / POR LO QUE SE', 'To the extent or degree of something', 'As far as I know, the movie will start in a few minutes.', null, null, 'AS FAR AS - I KNOW / POR LO QUE SE'),
('VERBS.pdf', 'idiom', 'As For', null, null, null, 'MY SELF / EN CUANTO A MÍ', 'With regard to, concerningw', '“As for myself, I think that I will return home now.”', null, null, 'AS FOR - MY SELF / EN CUANTO A MÍ'),
('VERBS.pdf', 'idiom', 'As If', null, null, null, 'COMO SI', 'In the same way that something would be, that', 'It seemed as if the whole school came to the concert.', null, null, 'AS IF - COMO SI'),
('VERBS.pdf', 'idiom', 'As Long As', null, null, null, 'MIENTRAS QUE', 'Provided that, on condition that', '“As long as you promise to be careful, you can borrow my car.”', null, null, 'AS LONG AS - MIENTRAS QUE'),
('VERBS.pdf', 'idiom', 'As Soon As', null, null, null, 'TAN PRONTO COMO', 'Just after something, when )\EQTPI -TLSRIHQ]JVMIRHEWWSSREW-ƙRMWLIH dinner.', null, null, null, 'AS SOON AS - TAN PRONTO COMO'),
('VERBS.pdf', 'idiom', 'As To', null, null, null, 'EN CUANTO A', 'With regard to, according to', '“As to your question, I will answer it tomorrow.”', null, null, 'AS TO - EN CUANTO A'),
('VERBS.pdf', 'idiom', 'As Well', null, null, null, 'TAMBIÉN', 'In addition, also, too', 'I plan to take swimming lessons this summer. I plan to take a computer course as well.', null, null, 'AS WELL - TAMBIÉN'),
('VERBS.pdf', 'idiom', 'As Well As (Someone Or Something) Como', null, null, null, 'ASI', 'In addition to someone or something', '“Please bring your swimming suit as well as your towel.”', null, null, 'AS WELL AS (SOMEONE OR SOMETHING) - ASI COMO'),
('VERBS.pdf', 'idiom', 'Back And Forth', null, null, null, 'DE AQUÍ PARA ALLÁ', '&EGO[EVHWERHJSV[EVHWƙVWXSRI[E]ERHXLIRXLI other way', 'The argument with the lawyer went back and forth before the judge made a decision.', null, 20, 'BACK AND FORTH - DE AQUÍ PARA ALLÁ'),
('VERBS.pdf', 'idiom', 'Better Off Break Down (Something) Or Break Break Up Or Break Up (Something) Or Break', null, null, null, 'MEJOR', 'To be in a better situation than before', 'My friend would be better off if he sold his old car and bought a new one. (SOMETHING) DOWN - DESGLOSAR To divide something into parts, to separate something into simpler substances  We tried to break down the problem for further study. (SOMETHING) UP - ROMPER To separate, to divide into groups or pieces, to put an end to something  I hope that my favorite band does not break up.', null, 20, 'BETTER OFF - MEJOR BREAK DOWN (SOMETHING) OR BREAK BREAK UP OR BREAK UP (SOMETHING) OR BREAK'),
('VERBS.pdf', 'idiom', 'By The Way', null, null, null, 'POR CIERTO', 'Incidentally', '“By the way, could you please bring your laptop computer tomorrow.”', null, 20, 'BY THE WAY - POR CIERTO'),
('VERBS.pdf', 'idiom', 'By The Way Carry Out (Something) Or Carry', null, null, null, 'POR CIERTO', 'Incidentally', '“By the way, could you please bring your laptop computer tomorrow.” (SOMETHING) OUT - LLEVAR ACABO To put something into action, to accomplish something, to do something  The scientist wanted to carry out more experiments before discussing the new medicine.', null, 20, 'BY THE WAY - POR CIERTO CARRY OUT (SOMETHING) OR CARRY'),
('VERBS.pdf', 'idiom', 'Come On!', null, null, null, 'OH VAMOS', 'Please, hurry, go faster', '“Come on, stop doing that.”', null, 20, 'COME ON! - OH VAMOS'),
('VERBS.pdf', 'idiom', 'Come Up', null, null, null, 'PASA DE LA NADA', 'To happen unexpectedly', 'I will not be able to go to the party if something else comes up.', null, 20, 'COME UP - PASA DE LA NADA'),
('VERBS.pdf', 'idiom', 'Come Up With (Something)', null, null, null, 'PROPONER', '8STVSHYGISVƙRHEXLSYKLXSVMHIESVERW[IV', 'I tried to come up with a name for the new magazine.', null, 20, 'COME UP WITH (SOMETHING) - PROPONER'),
('VERBS.pdf', 'idiom', 'Deal With (Something) End Up (Doing Something Or Going', null, null, null, 'TRATAR CON', 'To be concerned with something, to take action about something', 'We will deal with the boxes tomorrow.', null, 20, 'DEAL WITH (SOMETHING) - TRATAR CON END UP (DOING SOMETHING OR GOING'),
('VERBS.pdf', 'idiom', 'Somewhere)', null, null, null, 'TERMINAR', 'To do something that one had not planned to do, to go somewhere one had not planned to go', 'We ended up watching a movie last night.', null, 20, 'SOMEWHERE) - TERMINAR'),
('VERBS.pdf', 'idiom', 'Get Back To (Something)', null, null, null, 'REGRESAR', 'To return to something', 'I was happy to get back to my work after my holiday.', null, 21, 'GET BACK TO (SOMETHING) - REGRESAR'),
('VERBS.pdf', 'idiom', 'Get Into (Something) Argument With My Friend.', null, null, null, 'INVOLUCRARSE', 'To become interested or involved in something', 'I do not want to get into an Get into (somewhere) - entrar To enter somewhere.  My friend wants to get into a good university.', null, 21, 'GET INTO (SOMETHING) - INVOLUCRARSE ARGUMENT WITH MY FRIEND.'),
('VERBS.pdf', 'idiom', 'Get Out Of (Somewhere)', null, null, null, 'SALIR DE', 'To leave somewhere, to escape from somewhere', 'I have an appointment and I want to get out of my house quickly.', null, 21, 'GET OUT OF (SOMEWHERE) - SALIR DE'),
('VERBS.pdf', 'idiom', 'Get Rid Of (Something)', null, null, null, 'DESHACERSE DE', 'To give or throw something away, to sell or destroy something, to make a cold or fever disappear', 'I bought a new television so I want to get rid of my old one.', null, 21, 'GET RID OF (SOMETHING) - DESHACERSE DE'),
('VERBS.pdf', 'idiom', 'Get Through (Something)', null, null, null, 'LLEGAR AL FINAL', '/ FINALIZAR 8SGSQTPIXIWSQIXLMRKXSƙRMWLWSQIXLMRK', 'I have much reading that I must get through before tomorrow.', null, 21, 'GET THROUGH (SOMETHING) - LLEGAR AL FINAL'),
('VERBS.pdf', 'idiom', 'Go Ahead Figure Out (Someone Or Something) Or Figure(Someone Or Something)', null, null, null, 'SEGUIR ADELANTE', 'To begin to do something', '“Let`s go ahead and start now. We can`t wait any longer.”', null, 21, 'GO AHEAD - SEGUIR ADELANTE FIGURE OUT (SOMEONE OR SOMETHING) OR FIGURE(SOMEONE OR SOMETHING)'),
('VERBS.pdf', 'idiom', 'Out Fill In (Something) Or Fill (Something)', null, null, null, 'ENTENDER', 'To try to understand someone or something, to solve something )\EQTPI -ƙREPP]ƙKYVIHSYXLS[XSYWIXLIRI[ computer software.', null, null, 21, 'OUT - ENTENDER FILL IN (SOMETHING) OR FILL (SOMETHING)'),
('VERBS.pdf', 'idiom', 'In', null, null, null, 'RELLENAR', 'To write words in blank spaces. )\EQTPI Š4PIEWIƙPPMRXLMWJSVQERHKMZIMXXSXLI receptionist.” -ƙPPIHXLIJSVQMRERHKEZIMXXSXLIVIGITXMSRMWX', null, null, 21, 'IN - RELLENAR'),
('VERBS.pdf', 'idiom', 'Find Out (Something)', null, null, null, 'DESCUBRIR', 'To learn or discover something', 'My mother is angry with me because she found out that I had quit my French class.', null, 21, 'FIND OUT (SOMETHING) - DESCUBRIR'),
('VERBS.pdf', 'idiom', 'First Of All', null, null, null, 'PRIMERO QUE NADA', '8LIZIV]ƙVWXXLMRK', 'First of all, we prepared the garden and then we planted the seeds.', null, 21, 'FIRST OF ALL - PRIMERO QUE NADA'),
('VERBS.pdf', 'idiom', 'For Good', null, null, null, 'PARA SIEMPRE/PERMANENTEMENTE', 'Permanently', 'The city plans to close the public swim- ming pool for good.', null, 21, 'FOR GOOD - PARA SIEMPRE/PERMANENTEMENTE'),
('VERBS.pdf', 'idiom', 'For Sure Hang Out (Somewhere Or With Someone) Have (Something) To Do With (Something)', null, null, null, 'SIN DUDA', 'Without doubt, certainly, surely', '“I will go to the movie with you for sure next week.” - PASAR EL RATO To spend one`s time with no great purpose, to spend leisure time with friends  Recently, my friend has been hanging out with a bad group of people. - RELACIONADO CON To be about something, to be on the subject of something, to be related to something  “The book has something to do with cooking but I am not sure if you will like it.”', null, 21, 'FOR SURE - SIN DUDA HANG OUT (SOMEWHERE OR WITH SOMEONE) HAVE (SOMETHING) TO DO WITH (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Hold On', null, null, null, 'ESPERAR', 'To wait a minute, to stop, to wait and not hang up the phone', '“Please hold on for a minute while I lock the door.”', null, 22, 'HOLD ON - ESPERAR'),
('VERBS.pdf', 'idiom', 'In A Way', null, null, null, 'EN CIERTA FORMA', 'To a certain extent, a little, somewhat', 'In a way, I want to go to the new restaurant, but in a way I do not really care.', null, 22, 'IN A WAY - EN CIERTA FORMA'),
('VERBS.pdf', 'idiom', 'In Common', null, null, null, 'EN COMÚN', 'Shared together or equally, in use or ownership by all', 'I had nothing in common with the other members of the class.', null, 22, 'IN COMMON - EN COMÚN'),
('VERBS.pdf', 'idiom', 'In Detail', null, null, null, 'EN DETALLE', 'Giving all the details, item by item', 'The saleswoman explained the new product in detail.', null, 22, 'IN DETAIL - EN DETALLE'),
('VERBS.pdf', 'idiom', 'In Effect', null, null, null, 'EN EFECTO', 'For practical purposes, basically', 'The man’s silence was in effect a way of disagreeing with the other people at the meeting.', null, 22, 'IN EFFECT - EN EFECTO'),
('VERBS.pdf', 'idiom', 'In Fact', null, null, null, 'DE HECHO', 'Actually, the truth is', 'The man has been to China before. In fact, he has been there three times.', null, 22, 'IN FACT - DE HECHO'),
('VERBS.pdf', 'idiom', 'In Favor Of (Someone Or Something) Favor De', null, null, null, 'EN', 'To approve or support someone or something', 'Everybody is in favor of the new police chief.', null, 22, 'IN FAVOR OF (SOMEONE OR SOMETHING) - EN FAVOR DE'),
('VERBS.pdf', 'idiom', 'In General', null, null, null, 'EN GENERAL', 'In most situations or circumstances', 'In general, most of the people are happy with the new manager.', null, 22, 'IN GENERAL - EN GENERAL'),
('VERBS.pdf', 'idiom', 'In Order To', null, null, null, 'PARA', 'For the purpose of', 'They have decided to close down the school for the summer in order to do some major repairs.', null, 22, 'IN ORDER TO - PARA'),
('VERBS.pdf', 'idiom', 'In Other Words', null, null, null, 'EN OTRAS PALABRAS', 'In a different (usually more direct) way )\EQTPI Š-RSXLIV[SVHWMJ]SYHSRSXƙRMWLXLI assignment by Wednesday, you will not pass the course.”', null, null, 22, 'IN OTHER WORDS - EN OTRAS PALABRAS'),
('VERBS.pdf', 'idiom', 'In Place Keep (Someone Or Something) In Mind', null, null, null, 'EN ORDEN', 'In the proper place or location', 'Everything in the room was in place when we arrived for the meeting. - TENER EN MENTE To remember and think about someone or something  I told my friend to keep the time that I must leave for work in mind.', null, 22, 'IN PLACE - EN ORDEN KEEP (SOMEONE OR SOMETHING) IN MIND'),
('VERBS.pdf', 'idiom', 'Kind Of', null, null, null, 'MÁS O MENOS', 'A form of, more or less, moderately', 'I was kind of tired when I arrived home last night.', null, 23, 'KIND OF - MÁS O MENOS'),
('VERBS.pdf', 'idiom', 'Look For (Something) Look Up (Something) Or Look (Something)', null, null, null, 'BUSCAR (LUGAR)', '8SXV]XSƙRHWSQIXLMRKXSLYRXSVWIEVGLJSV something', 'My friend has been looking for her GVIHMXGEVHEPPQSVRMRKFYXWLIGERRSXƙRHMX', null, 23, 'LOOK FOR (SOMETHING) - BUSCAR (LUGAR) LOOK UP (SOMETHING) OR LOOK (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Up', null, null, null, 'BUSCAR (LECTURA)', 'To search for something in a dictionary or other book', 'I will look up my friend’s name in the telephone book.', null, 23, 'UP - BUSCAR (LECTURA)'),
('VERBS.pdf', 'idiom', 'Make A Difference', null, null, null, 'HACER LA DIFERENCIA', 'To cause a change in a situation, to change the nature of something', 'If I study hard this weekend, it should make a difference in my test results next week.', null, 23, 'MAKE A DIFFERENCE - HACER LA DIFERENCIA'),
('VERBS.pdf', 'idiom', 'Make Sense', null, null, null, 'TENER SENTIDO', 'To seem reasonable', 'The manager’s new proposal makes sense.', null, 23, 'MAKE SENSE - TENER SENTIDO'),
('VERBS.pdf', 'idiom', 'No Matter', null, null, null, 'NO IMPORTA / SIN IMPORTAR', 'Regardless', 'No matter how hard that I try, my QYWMGXIEGLIVMWRIZIVWEXMWƙIH', null, 23, 'NO MATTER - NO IMPORTA / SIN IMPORTAR'),
('VERBS.pdf', 'idiom', 'Not At All', null, null, null, 'PARA NADA', 'Certainly not, absolutely not', 'I am not at all happy with my new computer.', null, 23, 'NOT AT ALL - PARA NADA'),
('VERBS.pdf', 'idiom', 'Of Course / No Doubt Duda', null, null, null, 'POR SUPUESTO / SIN', '''IVXEMRP]HIƙRMXIP]REXYVEPP]', '“Of course you can use my car if you want to.”', null, 23, 'OF COURSE / NO DOUBT - POR SUPUESTO / SIN DUDA'),
('VERBS.pdf', 'idiom', 'On The Other Hand', null, null, null, 'POR OTRO LADO', 'However, in contrast, looking at the opposite side of a matter', 'He is very intelligent but on the other hand he is lazy and always gets low marks at school.', null, 23, 'ON THE OTHER HAND - POR OTRO LADO'),
('VERBS.pdf', 'idiom', 'Make Sure', null, null, null, 'ASEGURARSE', 'To make certain, to establish something without a doubt', 'I want to make sure that my friend will meet me tomorrow.', null, 23, 'MAKE SURE - ASEGURARSE'),
('VERBS.pdf', 'idiom', 'More Or Less Pick Up (Something) Or Pick (Something) Up Point Out (Someone Or Something) Or Point Put Out (Something) Or Put (Something)', null, null, null, 'MÁS O MENOS', 'Somewhat, to some extent', 'I more or less have decided to study business next year. - RECOGER To get or receive something, to choose and rise something  I picked up a copy of the newspaper at the station. (SOMEONE OR SOMETHING) OUT - SEÑALAR To explain or call attention to someone or something  My teacher was very kind when she pointed out the mistakes that I had made.', null, 23, 'MORE OR LESS - MÁS O MENOS PICK UP (SOMETHING) OR PICK (SOMETHING) UP POINT OUT (SOMEONE OR SOMETHING) OR POINT PUT OUT (SOMETHING) OR PUT (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Out Regardless Of (Something)', null, null, null, 'SACAR', 'To produce or make something (a product or brochure or report or CD or movie or paper)', 'The company puts out a newsletter every month for the employees. - INDEPENDIENTEMENTE DE Without considering or thinking about something, without regard to something, in spite of something  Regardless of the weather, we are going XSKSƙWLMRKXSQSVVS[QSVRMRK', null, 24, 'OUT - SACAR REGARDLESS OF (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Right Away', null, null, null, 'INMEDIATAMENTE', 'Immediately', '“I forgot my book at home but I will go and get it right away.”', null, 24, 'RIGHT AWAY - INMEDIATAMENTE'),
('VERBS.pdf', 'idiom', 'Run Into (Something', null, null, null, 'A FACT OR TROUBLE OR', null, null, null, 24, 'RUN INTO (SOMETHING - A FACT OR TROUBLE OR'),
('VERBS.pdf', 'idiom', 'Problems Or Difficulty) Set Up (Something) Or Set (Something) Up', null, null, null, 'ENCONTRARSE CON', 'To experience something, to encounter something', 'The mechanic ran into trouble when he [EWƙ\MRKQ]GEV - PREPARAR To establish something, to provide the money for something  The company set up a unique system to test the new product.', null, 24, 'PROBLEMS OR DIFFICULTY) - ENCONTRARSE CON SET UP (SOMETHING) OR SET (SOMETHING) UP'),
('VERBS.pdf', 'idiom', 'Show Up', null, null, null, 'APARECER', 'To appear, to arrive, to be present', '“What time did your friend show up for the party?”', null, 24, 'SHOW UP - APARECER'),
('VERBS.pdf', 'idiom', 'So Far', null, null, null, 'HASTA AHORA', 'Until now', 'So far, no one has entered the speech contest at the television station.', null, 24, 'SO FAR - HASTA AHORA'),
('VERBS.pdf', 'idiom', 'So To Speak', null, null, null, 'POR ASÍ DECIRLO', 'As one might or could say, this is one way to say something', 'We had a good time at the restaurant, so to speak, although the service was not very good.', null, 24, 'SO TO SPEAK - POR ASÍ DECIRLO'),
('VERBS.pdf', 'idiom', 'Sort Of (Something)', null, null, null, 'ALGO ASÍ', 'To be almost something, to be similar to something, to be not quite something )\EQTPI Š(MH]SYƙRMWLGPIERMRKXLIOMXGLIR#š “Sort of, but not really.”', null, null, 24, 'SORT OF (SOMETHING) - ALGO ASÍ'),
('VERBS.pdf', 'idiom', 'Stick With (Something) Take Advantage Of (Someone Or Something) Take Care Of (Someone Or Something) Take Out (Something) Or Take (Something)', null, null, null, 'SEGUIR CON', 'To continue doing something, to not quit something', 'The boy has been able to stick with his music lessons since he was a child. - TOMAR VENTAJAW 8SYWIWSQISRISVWSQIXLMRKJSVSRIŞWS[RFIRIƙX  We took advantage of the beautiful weather and went to the beach. - CUIDAR To look after or give attention to someone or something  It is good to take care of your health or you will become sick.', null, 24, 'STICK WITH (SOMETHING) - SEGUIR CON TAKE ADVANTAGE OF (SOMEONE OR SOMETHING) TAKE CARE OF (SOMEONE OR SOMETHING) TAKE OUT (SOMETHING) OR TAKE (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Out Take Over (Something) Or Take (Something)', null, null, null, 'REMOVER', 'To remove something from somewhere', 'The teacher told us to take out our books.', null, 25, 'OUT - REMOVER TAKE OVER (SOMETHING) OR TAKE (SOMETHING)'),
('VERBS.pdf', 'idiom', 'Over', null, null, null, 'TOMAR EL CONTROL', 'To take control of something, to take command of something', 'The large company wants to take over the small company in our town.', null, 25, 'OVER - TOMAR EL CONTROL'),
('VERBS.pdf', 'idiom', 'Take Place', null, null, null, 'OCURRIR', 'To happen, to occur', 'The soccer game took place on the coldest day of the year.', null, 25, 'TAKE PLACE - OCURRIR'),
('VERBS.pdf', 'idiom', 'To The Extent That', null, null, null, 'EN LA MEDIDA EN QUE', 'To the degree that, in so far as', 'I plan to provide information about the new company policy, to the extent  that I am familiar with it.', null, 25, 'TO THE EXTENT THAT - EN LA MEDIDA EN QUE'),
('VERBS.pdf', 'idiom', 'Up To Up To (Someone) To Decide (Something) Or', null, null, null, 'HASTA', 'Until, as far as a certain point, approaching a certain point', 'There were probably up to thirty people at the meeting.', null, 25, 'UP TO - HASTA UP TO (SOMEONE) TO DECIDE (SOMETHING) OR'),
('VERBS.pdf', 'idiom', 'Do (Something)', null, null, null, 'DEPENDE DE', 'To be responsible to choose or decide something', 'It is up to the company president to decide when the meeting will start.', null, 25, 'DO (SOMETHING) - DEPENDE DE'),
('VERBS.pdf', 'idiom', 'Used To (Something)', null, null, null, 'ACOSTUMBRADO A', 'Accustomed to something', 'My friend is not used to living in such a big city', null, 25, 'USED TO (SOMETHING) - ACOSTUMBRADO A'),
('VERBS.pdf', 'idiom', 'With Respect To (Something) Respecto A', null, null, null, 'CON', 'Referring to something, concerning something', 'I do not know what the company will do with respect to the old computer system.', null, 25, 'WITH RESPECT TO (SOMETHING) - CON RESPECTO A'),
('VERBS.pdf', 'idiom', 'Worked Out', null, null, null, 'FUNCIONÓ', 'To end successfully', 'In the end everything worked out well. www.facebook.com/E4CCSV www.facebook.com/E4CCGT www.facebook.com/E4CCHN www.facebook.com/E4CCNICARAGUA', null, 25, 'WORKED OUT - FUNCIONÓ')
on conflict (source_doc, category, term) do update set
  base_verb = excluded.base_verb,
  past = excluded.past,
  past_participle = excluded.past_participle,
  meaning_es = excluded.meaning_es,
  definition_en = excluded.definition_en,
  example_en = excluded.example_en,
  notes = excluded.notes,
  source_page = excluded.source_page,
  raw_text = excluded.raw_text,
  updated_at = now();
