// Generated by scripts/localize-curriculum-images.mjs.
// Keeps curriculum visuals independent from external hotlink availability.
import type { CurriculumLevel } from '../types';

export const curriculumImageMap: Record<string, string> = {
  "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1454165804606-c3d57bc86b40.jpg",
  "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1456513080510-7bf3a84b82f8.jpg",
  "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1461896836934-ffe607ba8211.jpg",
  "https://images.unsplash.com/photo-1473625247510-8ceb1760943f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1473625247510-8ceb1760943f.jpg",
  "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1476820865390-c52aeebb9891.jpg",
  "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1478131143081-80f7f84ca84d.jpg",
  "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1485846234645-a62644f84728.jpg",
  "https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1488085061387-422e29b40080.jpg",
  "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1488646953014-85cb44e25828.jpg",
  "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1493770348161-369560ae357d.jpg",
  "https://images.unsplash.com/photo-1494537176433-7a3c4ef2046f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1494537176433-7a3c4ef2046f.jpg",
  "https://images.unsplash.com/photo-1495364141860-b0d03eccd065?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1495364141860-b0d03eccd065.jpg",
  "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1497215728101-856f4ea42174.jpg",
  "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1497366216548-37526070297c.jpg",
  "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1499209974431-9dddcece7f88.jpg",
  "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1499364615650-ec38552f4f34.jpg",
  "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1499856871958-5b9627545d1a.jpg",
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1500382017468-9049fed747ef.jpg",
  "https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1501139083538-0139583c060f.jpg",
  "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1501504905252-473c47e087f8.jpg",
  "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1502086223501-7ea6ecd79368.jpg",
  "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1503387762-592deb58ef4e.jpg",
  "https://images.unsplash.com/photo-1503437313881-503a91226402?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1503437313881-503a91226402.jpg",
  "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1503614472-8c93d56e92ce.jpg",
  "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1503676260728-1c00da094a0b.jpg",
  "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1504608524841-42fe6f032b4b.jpg",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1504674900247-0877df9cc836.jpg",
  "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1506126613408-eca07ce68773.jpg",
  "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1506748686214-e9df14d4d9d0.jpg",
  "https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1506784365847-bbad939e9335.jpg",
  "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1506784983877-45594efa4cbe.jpg",
  "https://images.unsplash.com/photo-1507537509458-b8312d35a233?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1507537509458-b8312d35a233.jpg",
  "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1507608616759-54f48f0af0ee.jpg",
  "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1507679799987-c73779587ccf.jpg",
  "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1511512578047-dfb367046420.jpg",
  "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1511707171634-5f897ff02aa9.jpg",
  "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1511895426328-dc8714191300.jpg",
  "https://images.unsplash.com/photo-1512295767273-ac109ac3acfa?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1512295767273-ac109ac3acfa.jpg",
  "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1512436991641-6745cdb1723f.jpg",
  "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1512453979798-5ea266f8880c.jpg",
  "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1513542789411-b6a5d4f31634.jpg",
  "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1513694203232-719a280e022f.jpg",
  "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1516321318423-f06f85e504b3.jpg",
  "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1516321497487-e288fb19713f.jpg",
  "https://images.unsplash.com/photo-1516387938699-a93567ec168e?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1516387938699-a93567ec168e.jpg",
  "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1517048676732-d65bc937f952.jpg",
  "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1517486808906-6ca8b3f04846.jpg",
  "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1517649763962-0c623066013b.jpg",
  "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1517849845537-4d257902454a.jpg",
  "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1518173946687-a4c8892bbd9f.jpg",
  "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1518770660439-4636190af475.jpg",
  "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1519389950473-47ba0277781c.jpg",
  "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1520607162513-77705c0f0d4a.jpg",
  "https://images.unsplash.com/photo-1520694478166-daaaaec95b69?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1520694478166-daaaaec95b69.jpg",
  "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1521791136064-7986c2920216.jpg",
  "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1522071820081-009f0129c71c.jpg",
  "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1522075469751-3a6694fb2f61.jpg",
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1522202176988-66273c2fd55f.jpg",
  "https://images.unsplash.com/photo-1522204523234-8729aa6e3d5f?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1522204523234-8729aa6e3d5f.jpg",
  "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1523240795612-9a054b0db644.jpg",
  "https://images.unsplash.com/photo-1523289333742-be1143f6b766?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1523289333742-be1143f6b766.jpg",
  "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1523482580672-f109ba8cb9be.jpg",
  "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1523961131990-5ea7c61b2107.jpg",
  "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1524661135-423995f22d0b.jpg",
  "https://images.unsplash.com/photo-1525362081669-2b476bb628c3?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1525362081669-2b476bb628c3.jpg",
  "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1525547719571-a2d4ac8945e2.jpg",
  "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1529333166437-7750a6dd5a70.jpg",
  "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1531482615713-2afd69097998.jpg",
  "https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1532453288672-3a27e9be9efd.jpg",
  "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1536440136628-849c177e76a1.jpg",
  "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1541781774459-bb2af2f05b55.jpg",
  "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1542838132-92c53300491e.jpg",
  "https://images.unsplash.com/photo-1543269664-76bc3997d9ea?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1543269664-76bc3997d9ea.jpg",
  "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1543269865-cbf427effbad.jpg",
  "https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1543286386-713bdd548da4.jpg",
  "https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1543852786-1cf6624b9987.jpg",
  "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1544367567-0f2fcb009e0b.jpg",
  "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1551698618-1dfe5d97d256.png",
  "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1552664730-d307ca884978.jpg",
  "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1554068865-24cecd4e34b8.jpg",
  "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1573496359142-b8d87734a5a2.jpg",
  "https://images.unsplash.com/photo-1596443686812-2f45229eebc3?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1596443686812-2f45229eebc3.jpg",
  "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1611162616305-c69b3fa7fbe0.jpg",
  "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800": "/images/curriculum-remote/1611162617474-5b21e879e113.jpg"
};

const restoredLocalImageVersions: Record<string, string> = {
  '/images/prep_between.jpg': '/images/prep_between.jpg?v=restored-20260820',
  '/images/directions_ask.jpg': '/images/directions_ask.jpg?v=restored-20260820',
  '/images/prep_in.jpg': '/images/prep_in.jpg?v=restored-20260820',
  '/images/prep_on.jpg': '/images/prep_on.jpg?v=restored-20260820',
  '/images/prep_under.jpg': '/images/prep_under.jpg?v=restored-20260820',
  '/images/prep_next_to.jpg': '/images/prep_next_to.jpg?v=restored-20260820',
  '/images/prep_across.jpg': '/images/prep_across.jpg?v=restored-20260820',
  '/images/directions_give.jpg': '/images/directions_give.jpg?v=restored-20260820',
  '/images/adults_c10_emoji.jpg': '/images/adults_c10_emoji.jpg?v=restored-20260820',
  '/images/teens_complete.jpg': '/images/teens_complete.jpg?v=restored-20260820',
  '/images/adults_c10_homework.jpg': '/images/adults_c10_homework.jpg?v=restored-20260820',
  '/images/adults_c10_video.jpg': '/images/adults_c10_video.jpg?v=restored-20260820',
  '/images/teens_welcome.jpg': '/images/teens_welcome.jpg?v=restored-20260820',
  '/images/teens_social_welcome.jpg': '/images/teens_social_welcome.jpg?v=restored-20260820',
  '/images/teens_apps.jpg': '/images/teens_apps.jpg?v=restored-20260820',
};

export function localizeCurriculumImages(levels: CurriculumLevel[]) {
  for (const level of levels) {
    for (const lesson of level.classes) {
      for (const section of lesson.sections) {
        for (const slide of section.slides) {
          if (!slide.imageUrl) continue;
          const localized = curriculumImageMap[slide.imageUrl] || slide.imageUrl;
          const cleanPath = localized.split(/[?#]/)[0];
          slide.imageUrl = restoredLocalImageVersions[cleanPath] || localized;
        }
      }
    }
  }
}
